name: CI MLflow

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'MLProject/Tautan ke Docker Hub.txt'

env:
  IMAGE_NAME: "knn-behavior"
  # Pastikan URI menggunakan path absolut
  MLFLOW_TRACKING_URI: "${{ github.workspace }}/MLProject/mlruns"

jobs:
  train-test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          pip install -r MLProject/requirements.txt
          pip install mlflow  

      - name: Run Modelling
        working-directory: ./MLProject
        run: python modelling.py

      - name: Get MLflow Metadata
        id: meta
        run: |
          # Mencari Run ID dan Experiment ID terbaru
          python -c "
          import mlflow
          import os
          uri = 'file://' + os.environ['MLFLOW_TRACKING_URI']
          mlflow.set_tracking_uri(uri)
          exp = mlflow.get_experiment_by_name('Eksperimen_SML_KNN_Erza')
          runs = mlflow.search_runs(experiment_ids=[exp.experiment_id], order_by=['attribute.start_time DESC'])
          
          run_id = runs.iloc[0].run_id
          exp_id = exp.experiment_id
          
          # Simpan ke environment variable untuk step berikutnya
          with open(os.environ['GITHUB_ENV'], 'a') as f:
              f.write(f'RUN_ID={run_id}\n')
              f.write(f'EXP_ID={exp_id}\n')
          "

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          FULL_TAG="${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          
          # MLflow menyimpan model di: mlruns/<experiment_id>/<run_id>/artifacts/model
          MODEL_PATH="mlruns/745624129257364331/models/m-b4213cdac1fd4d4885f9de1540bf8c48/artifacts/model"
          
          echo "Building Docker from path: $MODEL_PATH"

          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "workflow_temp" 

          # Tag ulang ke format Docker Hub
          docker tag workflow_temp "$FULL_TAG"
          docker push "$FULL_TAG"

      - name: Upload Experiment Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-backup
          path: ./MLProject/mlruns
