name: Train and Deploy

on:
  push:
    branches: ["master"]
    paths-ignore:
      - './MLProject/Tautan ke Docker Hub.txt'

env:
  IMAGE_NAME: "KNN-Behavior"
  MLFLOW_TRACKING_URI: "./MLProject/mlruns"

jobs:
  train-test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.10"

      - name: Install Dependencies
        run: pip install -r MLProject/requirements.txt

      - name: Run Modelling
        working-directory: ./MLProject
        run: python modelling.py

      - name: Upload Experiment Logs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-backup
          path: ./MLProject/mlruns

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          FULL_TAG="${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
  
          mlflow models build-docker \
            -m "models:/knn_model/latest" \
            -n "$FULL_TAG"
  
          docker push "$FULL_TAG"
