name: CI MLflow

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'MLProject/Tautan ke Docker Hub.txt'

env:
  IMAGE_NAME: "knn-behavior"
  # Menggunakan path absolut agar MLflow CLI tidak bingung
  MLFLOW_TRACKING_URI: "${{ github.workspace }}/MLProject/mlruns"

jobs:
  train-test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          pip install -r MLProject/requirements.txt
          pip install mlflow  

      - name: Run Modelling
        working-directory: ./MLProject
        run: python modelling.py

      - name: Get latest Run ID
        id: get_run_id
        run: |
          # Kita cari Run ID terbaru dari eksperimen yang dibuat modelling.py
          RUN_ID=$(python -c "
          import mlflow
          import os
          mlflow.set_tracking_uri('file://' + os.environ['MLFLOW_TRACKING_URI'])
          runs = mlflow.search_runs(experiment_names=['Eksperimen_SML_KNN_Erza'], order_by=['attribute.start_time DESC'])
          print(runs.iloc[0].run_id)
          ")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          FULL_TAG="${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          
          # Folder 'model' adalah default dari mlflow.autolog()
          mlflow models build-docker \
            -m "runs:/bbad8bfe5c72456b865f0ad15d824159/model" \
            -n "workflow_temp" \

          # Tag ulang image dari mlflow ke format Docker Hub
          docker tag workflow_temp "$FULL_TAG"
          docker push "$FULL_TAG"

      - name: Upload Experiment Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-backup
          path: ./MLProject/mlruns
